version: "3.9"

services:
  web:
    image: rg.fr-par.scw.cloud/clement-registry/todo-front-end
    ports:
      - "80:80"
    depends_on:
      - api
      - db
  api:
    image: rg.fr-par.scw.cloud/clement-registry/todo-back-end
    depends_on:
      - db
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - "dbdata:/var/lib/mysql"

volumes:
  dbdata:
