version: "3.9"

services:
  web:
    build:
      context: ./front-end
      dockerfile: Dockerfile-dev
    ports:
      - "3300:3000"
    volumes:
      - "${HOME}/progression/projects/todo-app/front-end/src:/app/src"
    depends_on:
      - api
  api:
    build:
      context: ./back-end
      dockerfile: Dockerfile-dev
    environment:
      TYPEORM_HOST: db
    ports:
      - "3001:3000"
    volumes:
      - "${HOME}/progression/projects/todo-app/back-end/src:/app/src"
    depends_on:
      - db
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: todo
    volumes:
      - "dbdata:/var/lib/mysql"
    ports:
      - "3306:3306"
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  dbdata:
