version: "3.9"

services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: todo
    volumes:
      - dbdata:/var/lib/mysql
  api:
    image: rg.fr-par.scw.cloud/clement-registry/todo-back-end
    ports:
      - "3000:3000"
    env_file: "./back-end/.env"
    depends_on:
      - db
  web:
    image: rg.fr-par.scw.cloud/clement-registry/todo-front-end
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api
    volumes:
      - /etc/letsencrypt/:/etc/nginx/ssl/:rw
      - /var/www/certbot/:/var/www/certbot/:rw
      - /var/log/nginx/:/var/log/nginx/:rw

volumes:
  dbdata:
