# pull official base image
FROM node:18-alpine

WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH

COPY package.json ./ 
COPY package-lock.json ./
RUN npm install -g npm@latest
RUN npm install
COPY . ./

CMD ["npm", "run", "start:dev"]
